// Medicine
export const GET_MEDICINES_LOADING = "GET_MEDICINES_LOADING"
export const GET_MEDICINES = "GET_MEDICINES"
export const GET_MEDICINES_FAILED = "GET_MEDICINES_FAILED"

export const ADD_MEDICINE = "ADD_MEDICINE"
export const ADD_MEDICINE_FAILED = "ADD_MEDICINE_FAILED"

export const DELETE_MEDICINE = "DELETE_MEDICINE"
export const DELETE_MEDICINE_FAILED = "DELETE_MEDICINE_FAILED"

export const UPDATE_MEDICINE = "UPDATE_MEDICINE"
export const UPDATE_MEDICINE_FAILED = "UPDATE_MEDICINE_FAILED"

export const REMOVE_ERROR = "REMOVE_ERROR"

// Patient
export const REMOVE_PATIENT_ERROR = "REMOVE_PATIENT_ERROR"
export const GET_PATIENT_LOADING = "GET_PATIENT_LOADING"
export const GET_PATIENT = "GET_PATIENT"
export const GET_PATIENT_FAILED = "GET_PATIENT_FAILED"

export const ADD_PATIENT = "ADD_PATIENT"
export const ADD_PATIENT_FAILED = "ADD_PATIENT_FAILED"

export const DELETE_PATIENT = "DELETE_PATIENT"
export const DELETE_PATIENT_FAILED = "DELETE_PATIENT_FAILED"

export const UPDATE_PATIENT = "UPDATE_PATIENT"
export const UPDATE_PATIENT_FAILED = "UPDATE_PATIENT_FAILED"

// Treatment
export const REMOVE_TREATMENT_ERROR = "REMOVE_TREATMENT_ERROR"
export const GET_TREATMENT_LOADING = "GET_TREATMENT_LOADING"
export const GET_TREATMENT = "GET_TREATMENT"
export const GET_TREATMENT_FAILED = "GET_TREATMENT_FAILED"

export const ADD_TREATMENT = "ADD_TREATMENT"
export const ADD_TREATMENT_FAILED = "ADD_TREATMENT_FAILED"

export const DELETE_TREATMENT = "DELETE_TEREATMENT"
export const DELETE_TREATMENT_FAILED = "DELETE_TEREATMENT_FAILED"

export const UPDATE_TREATMENT = "UPDATE_TREATMENT"
export const UPDATE_TREATMENT_FAILED = "UPDATE_TREATMENT_FAILED"

// GetAllDetails (Patient + Treatment + appoinment)
export const GET_ALLDETAILS = "GET_ALLDETAILS"
export const GET_ALLDETAILS_FAILED = "GET_ALLDETAILS_FAILED"

// Appoinment
export const GET_APPOINMENTS = "GET_APPOINMENTS"
export const GET_APPOINMENTS_FAILED = "GET_APPOINMENTS_FAILED"

export const APPROVE_APPOINMENT = "APPROVE_APPOINMENT"
export const APPROVE_APPOINMENT_FAILED = "APPROVE_APPOINMENT_FAILED"

export const DELETE_APPOINMENT = "DELETE_APPOINMENT"
export const DELETE_APPOINMENT_FAILED = "DELETE_APPOINMENT_FAILED"