// SignUp

export const CLEAR_ERROR="CLEAR_ERROR"

export const SET_TOKEN="SET_TOKEN" 
export const REMOVE_TOKEN="REMOVE_TOKEN"

//signup
export const SIGNUP="SIGNUP"
export const SIGNUP_FAILED="SIGNUP_FAILED"
export const AFTER_SIGNUP="AFTER_SIGNUP"

//signin
export const SIGNIN="SIGNIN"
export const SIGNIN_FAILED="SIGNIN_FAILED"

//forgot password
export const CHECK_EMAIL="CHECK_EMAIL"
export const CHECK_EMAIL_FAILED="CHECK_EMAIL_FAILED" 

export const CHECK_OTP="CHECK_OTP"
export const CHECK_OTP_FAILED="CHECK_OTP_FAILED"

export const CHANGE_PASSWORD="CHANGE_PASSWORD"
export const CHANGE_PASSWORD_FAILED="CHANGE_PASSWORD_FAILED"

//end forgot password

export const GET_USER_DETAILS="GET_USER_DETAILS"
export const GET_USER_DETAILS_FAILED="GET_USER_DETAILS_FAILED"

export const GET_USER_ALL_DETAILS="GET_USER_ALL_DETAILS"
export const GET_USER_ALL_DETAILS_FAILED="GET_USER_ALL_DETAILS_FAILED"

export const UPDATE_USER_DETAILS="UPDATE_USER_DETAILS"
export const UPDATE_USER_DETAILS_FAILED="UPDATE_USER_DETAILS_FAILED"

export const UPDATE_PASSWORD="UPDATE_PASSWORD"
export const UPDATE_PASSWORD_FAILED="UPDATE_PASSWORD_FAILED"

// Appoinment

export const ALL_APPOINMENT="ALL_APPOINMENT"
export const ALL_APPOINMENT_FAILED="ALL_APPOINMENT_FAILED"

export const BOOK_APPOINMENT="BOOK_APPOINMENT"
export const BOOK_APPOINMENT_FAILED="BOOK_APPOINMENT_FAILED"

export const UPDATE_APPOINMENT="UPDATE_APPOINMENT"
export const UPDATE_APPOINMENT_FAILED="UPDATE_APPOINMENT_FAILED"

export const DELETE_APPOINMENT="DELETE_APPOINMENT"
export const DELETE_APPOINMENT_FAILED="DELETE_APPOINMENT_FAILED"

// end Appoinment